# Introduction 

This document provides a detailed summary of select data sources that may be used to support stock assessments of West Coast groundfish in `r assess_year` and beyond. At the March 2026 Pacific Fisheries Management Council (the Council) meeting, an earlier version of this document was presented that included only data from federal surveys. This version includes all information in the March version, but has included additional information based upon the Council motion requested additional information for select species to support final decision making.

This summary includes sampling data (i.e., length, age, and unread age structures) from the Northwest Fisheries Science Center (NWFSC) West Coast Groundfish Bottom Trawl Survey (WCGBTS) and Southern California Hook and Line Survey (HKLS) for the species and stock areas included in the Pacific Coast Groundfish Fishery Management Plan. For species with robust sampling, relative indices of abundance and sampled length compositions by year and source are also provided. A summary of the available maturity data collected by scientists at the NWFSC for each species is also provided.

For select species identified at the March 2026 Council meeting, additional information from commercial, recreational, California Collaborative Fisheries Research Program (CCFRP) Survey, and the Groundfish Cooperative Data Collection (GCDC) is also provided. Select additional species that were mentioned in advisory panel and management reports to support additional discussion at the June Council meeting. The species where additional information is provided include: black rockfish off Oregon and Washington, bocaccio, lingcod north and south of 40$^\circ$ 10' N. latitude, longspine thornyhead, Pacific spiny dogfish, petrale sole, redbanded rockfish, shortspine thornyhead, widow rockfish, and yellowtail rockfish south of 40$^\circ$ 10' N. latitude.

# Data

## Data avialable for all species

### NWFSC West Coat Groundfish Bottom Trawl Survey (WCGBTS)

The NWFSC WCGBTS is a fishery-dependent survey based on a random-grid design, covering coastal waters (55-1,280 m) from the US - Canada border south to the US - Mexico border twice each year from May to October. The survey uses chartered commercial fishing vessels and an Aberdeen-style trawl net. 

Biological data samples collected by the NWFSC WCGBTS between 2003-`r endyr`, average number of tows that observe each species by year, relative indices of abundance for species with sufficient observations, and visualizations of length composition data.

### NWFSC Hook and Line Survey (HKLS)

The NWFSC HKLS is a fishery-dependent survey conducted annually in the Southern California Bight using rod and reel gear at fixed stations to target shelf rockfish in the genus *Sebastes*.

Biological data samples collected by the NWFSC HKLS from 2004-`r endyr`, the average number of sets that observe each species by year, relative indices of abundance for species with sufficient observations, and visualizations of length composition data.

### Survey length compositions

The length data collected by the WCGBTS were expanded using a generalized area-based stratification. The expanded length composition data were summarized using either a 2 or 4 cm bin structure depending upon the range between maximum and minimum lengths observed within the survey data. All length observations were grouped as unsexed fish for plotting to reveal potential trends in length compositions across time. 

The length data collected by the HKLS were summarized to reflect the proportion of observations by species, length bin, and year. The length composition data were summarized using either a 2 or 4 cm bin structure depending upon the range between maximum and minimum lengths observed within the survey data, in the same manner as for the WCGBTS data. 

The generalized approach for expanding the length composition data and bin structure provides a simple summary of the data that can be useful for decision making, but will likely differ from a species-specific approach that would be applied in a future assessment. Additionally, it is important to note that each survey's selectivity for each species will impact the lengths observed and has not been explicitly accounted for in this analysis.

### Survey relative indices of abundance

Indices of abundance were estimated from the WCGBTS using a spatiotemporal model (`sdmTMB`) for species well-observed by the survey. The indices were estimated using a generalized configuration across species using either a gamma, log-normal, or Tweedie distribution, with the dispersion parameter held constant across years with 200-500 knots used to create the mesh. The model structure for each species is provided in Section \ref{wcgbt-index-settings}. Species-specific indices of abundance produced for past assessments or produced for future assessments may use a modified model structure resulting in slight changes in year-by-year values for the indices of abundance presented in this document. 

Indices of abundance were estimated from the HKLS for well-observed species using `sdmTMB` with a negative-binomial error structure with covariates for year, site, and drop number. The model structure is provided in Section \ref{hkl-index-settings}. Additional covariates or error-structures to develop species-specific indices were not explored in this analysis.

The indices of abundance presented here should only be considered illustrative of potential trends in abundance across time.

### Maturity data collections

Maturity samples for a wide range of West Coast groundfish species have been collected across multiple sources: the WCGBTS, the HKLS, the Pacific hake acoustic survey, at-sea sampling from the Pacific hake fishery, and port sampling by state agencies. A summary of the number of maturity samples collected and read between 2009 - 2024 is provided for each species. These data summaries only include collections led by the NWFSC but other collections could be available from other research groups.     

## Additional information for select species

### Commcerical 

Add info

Biological data samples collected from commercial fisheries between 2000-`r endyr` in terms of length, age, and unread age structure samples by year and species from California, Oregon, and Washington.

### Recreational

Add info

Biological data samples collected from recreational fisheries in terms of length (California 2004-`r endyr`, Oregon and Washington 2000-`r endyr`), ages, and unread age structures samples (California 2022-`r endyr` ad-hoc collections, Oregon 2000-2024, and Washington 2000-`r endyr`) by year and species from California, Oregon, and Washington.

#### California recreational age-structure collections

California Department of Fish and Wildlife (CDFW) provided age structure sample numbers
collected via various methods from recreational fisheries. These samples were
collected outside the standard sampling protocol for California Recreational Fisheries
Survey (CRFS) sampling program. To date, there are no age or age structure sample data in RecFIN that have been collected from California recreational fisheries. Recent age structure collections from 2017-2025 were provided directly by CDFW. The recreational age structure collections provided by CDFW were collected by various methods: 1) from angler surrendered fish that were kept in excess of recreational bag limits or were prohibited to be retained, 2) cowcod collections under CDFW’s Exempted Fishing Permit encountered incidentally by Commercial Passenger Fishing Vessels, and 3) randomly sampled
species from private/rental and party/charter recreational vessels. Any future assessment, will need to investigate the California recreational age structures for representativeness to determine whether they could be linked to a recreational fleet within a model.

### California Collaborative Fisheries Research Program Survey (CCFRP)

Add info

Biological data samples collected  by the CCFRP Survey in terms of length samples (2007-2022) and unread age structure samples (2017-`r endyr`) for select species sampled in California.

### Groundfish Cooperative Data Collection (GCDC)

Add info

Biological data samples collected by the GCDC from 2023-`r endyr` for yellowtail rockfish south of 40$^\circ$ 10' N. latitude

### Catches

Add info

## Additional data not included in this report

Data may be available for consideration in future assessments that are currently not included in this report. A summary of potential additional data that could be available are described below:

* Totals for data collected in 2026 in PacFIN and RecFIN are incomplete for all 
states and these data would be included in any future assessment.

* Length data collected by the CCFPR survey in 2023-2025 were not available but would
be available for 2027 assessments. 

* Historical data collections from various research projects exist at the SWFSC that
have not been cataloged and entered into any database. There are available unread
otoliths for yellowtail rockfish south in this collection from various sources and 
historical years, however, specific information was not available for this report. 

* State may have substantial collections from periods prior to the years
summarized in this report from their commercial and recreational sampling programs.

* CDFW is undergoing a review of historical age structures collections (i.e., referred to
as refugia samples) for samples from the 1980s and earlier. If sufficient documentation
exists for these historical samples they could be potentially included in future assessments. Since this work is ongoing it is unclear how many samples may be available across species.

Finally, summarizing commercial and recreational data from each state accurately continues to be challenging due to differences by state in what information is transmitted to PacFIN and RecFIN. Receiving and understanding the available commercial and recreational data requires emailing various representative in each state who thankfully have been accommodating in answering questions and providing
additional data summaries. However, given the challenges around acquiring and collating,
data summaries may not be comprehensive or have unintentional errors. Any issues identified will be addressed in future versions.