# Introduction 

This document provides a detailed summary of commonly used data sources that may be used to support assessments in `r assess_year`. A detailed summary of data available by year and across sources can allow the Pacific Fishery Management Council (Council) and advisory bodies to understand the coverage of data across time and the potential viability of a new assessment or assessment type. 

HIGHLIGHT CHANGES TO THIS YEAR'S REPORT

## Biological Samples

Data from the Northwest Fisheries Science Center (NWFSC) West Coast Groundfish Bottom Trawl Survey (WCGBT) and NWFSC Hook-and-Line (HKL) surveys are summarized. 

Data collected by the NWFSC WCGBT survey between 2003-`r endyr` and the NWFSC HKL survey from 2004-`r endyr` are summarized by species. Lengths, aged fish, and unread age structures collected are available by year. Additionally, the number of tows (NWFSC WCGBT survey) or sites (NWFSC HKL survey) that observed each species by year are also provided.

## Survey Length Compositions

The length data collected by the NWFSC WCGBT survey were expanded using a generalized area-based stratification. The composition data were expanded using a design-based approach with strata based on state latitudes with two depth strata: 55 - 183 m and 183 - 549 m, with an exception for four species. The four species have considerable biomass at depths greater than 549 m: sablefish, Dover sole, longspine thornyhead, and shortspine thornyhead. Thus an additional depth strata that covered deeper waters, 549 - 1,280 m, for each state area was added. The expanded length composition data were summarized using either a 2 or 4 cm bin structure depending upon the range between maximum and minimum lengths observed within the survey data. Species where the range between the maximum and minimum lengths observed by the survey were less than 60 cm, 2 cm data bins were used, while for species where the range was 60 cm or greater the data bins were set at 4 cm. All length observations were treated as unsexed fish in this exercise for simplicity and for ease of observing potential trends in length observations across time. The generalized stratification and bin structure selected here provides a simple summary of the data that can be useful for decision making, but will likely differ from a species-specific approach that would be selected in a future assessment. Additionally, the NWFSC WCGBT survey selectivity for each species will impact the lengths observed and has not been explicitly accounted for in this analysis.

The length data collected by the NWFSC HKL survey were summarized to reflect the proportion of observations by species, length bin, and year. The length composition data were summarized using either a 2 or 4 cm bin structure depending upon the range between maximum and minimum lengths observed within the survey data, in the same manner as for the NWFSC WCGBT survey. Similar to the NWFSC WCGBT survey, the selectivity of the NWFSC HKL survey for each species will impact the lengths observed and has not been explicitly accounted for in this analysis.

## Survey Relative Indices of Abundance

Indices of abundance were estimated from the NWFSC WCGBT survey using a spatiotemporal model (smdTMB) for species well-observed by the survey. The indices were estimated using a generalized set-up across species using either a gamma or log-normal distribution, with the dispersion parameter held constant across years with 200-500 knots used to create the mesh. The model structure for each species is provided in Section \ref{wcgbt-index-settings}. Future species-specific indices of abundance created with sdmTMB would likely select a more tailored approach for model settings (e.g., knots, distributions) which could result in slight changes in year-by-year values for the indices of abundance. The indices of abundance presented here should only be considered illustrative of potential trends in abundance across time. 

Indices of abundance were estimated from the NWFSC HKL survey for well-observed species using a negative-binomial model that accounted for year, site, and drop number. Additional covariates that would typically be explored when developing species-specific indices for use in stock assessments were not explored in this analysis for simplicity. The selection of how to model these data for a particular species may vary from the approach applied here. For example, the recent vermilion and sunset rockfish assessment modeled the data as two indices (i.e., one for areas outside of the Cowcod Conservation Areas [CCA] and one for sites inside the CCAs). In contrast, the recent assessment of copper rockfish estimated a single index with observations by areas weighted (nearshore sites, northern Channel Islands, Southern Channel Islands). 

## Maturity Data Collections

Maturity samples for a wide range of West Coast groundfish species have been collected across a range of sources: NWFSC WCGBT survey, NWFSC HKL survey, Pacific hake survey, at-sea sampling of the Pacific hake fishery, and port sampling by ODFW and WDFW. Samples have been collected between 2009 - 2024. The following summary does not include collection from the 2025 NWFSC WCGBT and HKL surveys. Summaries of the maturity collections is provided for each species. This data summary only includes collections led by the NWFSC but other collections could be available at the SWFSC, CDFW, ODFW, WDFW, or other research groups. Future data summaries will look to integrate these additional collections in subsequent versions of this document.     

## Additional Data

Data may be available for consideration in future assessments that are currently not included in this report. A summary of potential additional data that could be available are described below:

* PacFIN and RecFIN. 

* Emphasize again that this is only survey data.

\newpage
